server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置需要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange的名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: atguiguA       #设置消息分组

eureka: # 客户端进行eureka注册的配置
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 2  # 设置心跳的时间间隔
    lease-renewal-interval-in-seconds: 5     # 如果现在超过了5秒的间隔（默认90秒）
    instance-id: receive-8803.com               # 在信息列表显示主机名称
    prefer-ip-address: true                  # 访问的路径变为IP地址
