server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com # eureka服务端的实例名称
  client:
    # false 表示不向注册中心注册自己。
    register-with-eureka: false
    # false 表示自己 就是 注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    # 关闭eureka自我保护机制，并自己设置中断时间
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000