server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route   # payment route  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001           # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**             # 断言，与路径相匹配的进行路由

        - id: payment_route2                   # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service
#          uri: http://localhost:8001           # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**              # 断言，与路径相匹配的进行路由
#            - After=2020-04-26T13:31:08.984+08:00[Asia/Shanghai] # After,Before,Between
#            - Cookie=username,Bridge_Wang
#            - Header=X-Request-Id, \d+
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，从而可以使用微服务名称而不是端口来进行路由。

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka